version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: cluster_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save "900 1 300 10 60 10000"
      --appendonly yes
      --appendfsync everysec
      --dir /data
    volumes:
      - ./data/redis:/data

  minio:
    image: quay.io/minio/minio
    container_name: cluster_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./data/minio:/data

  flask:
    build: ./app
    container_name: cluster_flask
    restart: unless-stopped
    ports:
      - "5100:5000"
    depends_on:
      redis:
        condition: service_started
    environment:
      REDIS_HOST: redis
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123

      TS_IP: "${TS_IP}"
    volumes:
      - /tmp/k3s_join_info.json:/tmp/k3s_join_info.json:ro
